name: CI
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.config.kind }} ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        config:
          - os: macOS-latest
            kind: test
          - os: windows-latest
            kind: test
          - os: ubuntu-latest
            kind: test
          - os: ubuntu-latest
            kind: lint
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.10.3
      - name: Check formatting
        if: matrix.config.kind == 'lint'
        run: |
          deno fmt --check
          deno lint
      - name: Test
        if: matrix.config.kind == 'test'
        run: |
          deno test
      - name: Test unstable
        if: matrix.config.kind == 'test'
        run: |
          deno test --coverage=./cov
      - name: Test coverage
        if: matrix.config.kind == 'test'
        run: |
          deno coverage ./cov
      - name: Release info
        if: |
          matrix.config.kind == 'test' &&
          github.repository == 'udibo/oauth2_server' &&
          startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          deno coverage --lcov ./cov > cov.lcov
      - name: Release
        uses: softprops/action-gh-release@v1
        if: env.RELEASE_VERSION != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: cov.lcov
